import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header/Header";
import { Footer } from "../components/Footer/Footer";
import { Homepage } from "../components/Home/Homepage";
import globalStyles from "../styles/Global.module.scss";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>LinguaHub - Английский в кайф</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={globalStyles.wrapper}>
        <Header />
        <Homepage />
        <Footer />
      </div>
    </div>
  );
};

export default Home;
